language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t loy124/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true loy124/react-test-app npm run test

after_success:
  #각 이미지 빌드 
  - docker build -t loy124/docker-frontend ./frontend
  - docker build -t loy124/docker-backend ./backend
  - docker build -t loy124/docker-nginx ./nginx
  #도커 허브 로그인
  #아이디는 travis CI 홈페이지에 미리 넣어준다.
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  #빌드된 이미지들을 도커 허브에 push
  - docker push loy124/docker-frontend
  - docker push loy124/docker-backend
  - docker push loy124/docker-nginx